spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
  application:
    name: ms-human
  datasource:
    url: jdbc:mysql://localhost:3306/foo_fighters
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
#    hibernate:
#      ddl-auto: update
    show-sql: true
  liquibase:
    change-log: classpath:/liquibase/changelog-master.yml
    enabled: true
server:
  port: 8080

api:
  url: http://localhost:9090